safe:        false
auto:        false

source:      .
destination: _site
layouts:     ./_layouts

future:      true
lsi:         false
pygments:    false

markdown: kramdown

relative_permalinks: false

url: "http://bolorkhuu.de"
baseurl: ''


plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
