safe:        false
auto:        false

source:      .
destination: _site
layouts:     ./_layouts

future:      true
lsi:         false
pygments:    false

markdown: kramdown

relative_permalinks: false

baseurl: ''
gems:
  - jekyll-redirect-from
